### ISSUE TITLE
Question feedback suggestions

### ISSUE THREAD

**Issue by tanjunchen** [fanux/kube-dev-book#5]
Any question?

催更
Kubernetes demo 是什么版本？目前 kubernetes 迭代速度很快，几个月就一版

**Comment by tanjunchen** [comment]
催更 +1

**Comment by fanux** [comment]
确实有些偏差，但是还好client-go接口层变化不大，会有变化，我是1.17.4 demo。 我觉得通过代码更深入理解原理 以不变应万变比较好
